apiVersion: v1
kind: Config
clusters:
- cluster:
    api-version: v1
    certificate-authority-data: 
    server: "https://192.168.50.101:6443"
  name: "local"
contexts:
- context:
    cluster: "local"
    user: "kube-admin-local"
  name: "local"
current-context: "local"
users:
- name: "kube-admin-local"
  user:
    client-certificate-data: 